### ISSUE TITLE
Is it possible to avoid using the Resources folder?

### ISSUE THREAD

**Issue by beardordie** [ATHellboy/ScriptableObjectDropdown#1]
From Unity Manual https://docs.unity3d.com/Manual/BestPracticeUnderstandingPerformanceInUnity6.html

> The Resources folder is a common source of many problems in Unity projects. Improper use of the Resources folder can bloat the size of a project’s build, lead to uncontrollable excessive memory utilization, and significantly increase application startup times.

Is it possible to avoid the need to put the objects in the Resources folder to get this functionality?

**Comment by ATHellboy** [comment]
Hey @beardordie 
Thanks for issue reporting.

I use loading from Resources folder (`LoadAll`) just when new thing is added to the project and it is done in Editor mode. Also I just load `ScriptableObject`s which they don't have much size in project build (Also memory utilization and application startup). Using Resources folder for materials, textures, prefabs and other big things is not recommended mostly.

But I will replace `Resources` with `AssetDatabase` for better performance and stuff.
