### ISSUE TITLE
Removing requirement of ScriptableObjectReference

### ISSUE THREAD

**Issue by LaneF** [ATHellboy/ScriptableObjectDropdown#2]
Nice work on the tool, thanks for making it available.

If there's no need for interface support is it possible to entirely remove ScriptableObjectReference?

In practice it is very inconvenient to actually use ScriptableObjectReference in place of real types where you want a dropdown. It would be much better if fields simply needed the Attribute with the Type in order to become a dropdown of that type pointing to the asset.

**Comment by ATHellboy** [comment]
Hey there,
Thank you very much.
Because of Interface support, I had to add ScriptableObjectReference but if you don't want Interface usage you can download version 1.1 from Releases page. It is what you want.
