### ISSUE TITLE
2020.1.14f1

### ISSUE THREAD

**Issue by AldeRoberge** [ATHellboy/ScriptableObjectDropdown#3]
![image](https://user-images.githubusercontent.com/4276275/100945157-ae78ed00-34ce-11eb-8255-2d890cbfec02.png)

Is it supposed to work for Unity 2020?

This is what I get.

**Comment by ATHellboy** [comment]
Hey @AldeRoberge,

It works on Unity 2020.1.15. So I think, there isn't any problems with Unity 2020.1.14 either.
Please check out [Usage Example](https://github.com/ATHellboy/ScriptableObjectDropdown#usage-example).

I think, that happens because of not using ScriptableObjectReference class.

``` cs
using UnityEngine;

[CreateAssetMenu(menuName = "Create Block")]
public class Block : ScriptableObject
{
    // Some fields
}
```

``` cs
using ScriptableObjectDropdown;
using UnityEngine;

public class BlockManager : MonoBehaviour
{
    // Without grouping (default is None)
    [ScriptableObjectDropdown(typeof(Block))] public ScriptableObjectReference targetBlock;
    // By grouping
    [ScriptableObjectDropdown(typeof(Block), grouping = ScriptableObjectGrouping.ByFolder)]
    public ScriptableObjectReference targetBlockByGrouping;
}
```
